name: shopping_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.6.0-91.0.dev

dependencies: 
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1

  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

